// src/design-tool/components/ThreeDPreviewModal.jsx
import React, { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Loader2, X, Box, Image as ImageIcon } from "lucide-react";
import Tshirt3DPreview from '../preview3d/Tshirt3DPreview';

// --- 1. THE WARP ENGINE (Pure JS Canvas Math) ---
// This function takes the flat design and "crunches" the edges to fake 3D curvature
const generateWarpedMugView = (textureUrl, viewSide) => {
    return new Promise((resolve) => {
        if (!textureUrl) return resolve(null);

        const img = new Image();
        img.crossOrigin = "Anonymous";
        img.src = textureUrl;

        img.onload = () => {
            const canvas = document.createElement('canvas');
            const ctx = canvas.getContext('2d');

            // We assume the input texture is a "Full Wrap" (approx 2.5:1 ratio)
            // We want to slice out 1/3rd of it for the current view.
            const totalWidth = img.width;
            const sliceWidth = totalWidth / 3;
            const height = img.height;

            // Set output size (high res)
            canvas.width = sliceWidth;
            canvas.height = height;

            // Determine which segment of the design to grab
            let sourceXStart = 0;
            if (viewSide === 'front') sourceXStart = sliceWidth;       // Center
            if (viewSide === 'right') sourceXStart = sliceWidth * 2;   // Right Side
            // 'left' starts at 0

            // --- THE MATH: Cylinder Projection ---
            const outputWidth = canvas.width;

            // Loop through every vertical column of the OUTPUT image
            for (let x = 0; x < outputWidth; x++) {
                // Normalize x from -1 (left edge) to 1 (right edge)
                let n = (x / outputWidth) * 2 - 1;

                // Math.asin calculates the curve. 
                // Pixels near the center (n=0) change little. 
                // Pixels near edge (n=1) get fetched from further away, creating the "squish".
                let textureXOffset = (Math.asin(n) / (Math.PI / 2)) * (sliceWidth / 2) + (sliceWidth / 2);

                let finalSourceX = sourceXStart + textureXOffset;

                // Clamp to prevent glitches
                if (finalSourceX < sourceXStart) finalSourceX = sourceXStart;
                if (finalSourceX > sourceXStart + sliceWidth) finalSourceX = sourceXStart + sliceWidth;

                // Draw a 1px vertical strip
                // We draw 1.5px width to prevent tiny gaps (aliasing) between strips
                ctx.drawImage(
                    img,
                    finalSourceX, 0, 1.5, height, // Source Slice
                    x, 0, 1, height               // Destination Strip
                );
            }
            resolve(canvas.toDataURL());
        };
        img.onerror = () => resolve(null);
    });
};

export function ThreeDPreviewModal({
    isOpen,
    onClose,
    textures,
    onAddToCart,
    isSaving,
    productId,
    productData = {},
    selectedColor = "#FFFFFF"
}) {
    const has3D = !!productData.model3d;
    const mockups = productData.mockups || {};
    const mockupKeys = Object.keys(mockups);

    // Detect Mug
    const isMug = productData?.title?.toLowerCase().includes("mug") ||
        productData?.category?.toLowerCase().includes("mug");

    const [viewMode, setViewMode] = useState('2d');
    const [activeSide, setActiveSide] = useState(mockupKeys[0] || 'front');

    // State to hold the "Curved" image generated by our function
    const [warpedTextureSrc, setWarpedTextureSrc] = useState(null);
    const [isProcessing, setIsProcessing] = useState(false);

    // Reset when modal opens
    useEffect(() => {
        if (isOpen) {
            // FIX: If it is a Mug, force default to '3d' view (skipping 2d)
            if (isMug && has3D) {
                setViewMode('3d');
            } else {
                setViewMode('2d');
            }
            setActiveSide(mockupKeys[0] || 'front');
        }
    }, [isOpen, productId, isMug, has3D]);

    // --- 2. GENERATE WARP EFFECT ---
    useEffect(() => {
        if (isOpen && isMug && viewMode === '2d' && textures.front?.url) {
            setIsProcessing(true);
            // Always use 'front' texture for mugs as it contains the full wrap
            generateWarpedMugView(textures.front.url, activeSide)
                .then(url => {
                    setWarpedTextureSrc(url);
                    setIsProcessing(false);
                });
        } else {
            setWarpedTextureSrc(null);
        }
    }, [activeSide, isMug, isOpen, textures, viewMode]);

    // Helper for T-Shirts (Non-Mugs)
    const getStandardTexture = () => {
        if (activeSide === 'left' || activeSide === 'right') return textures.front?.url;
        return textures[activeSide]?.url;
    };

    console.log(activeSide)

    return (
        <Dialog open={isOpen} onOpenChange={onClose}>
            <DialogContent className="w-[100vw] h-[100vh] p-0 gap-0 bg-zinc-950 border-zinc-800 flex flex-col overflow-hidden rounded-xl shadow-2xl">
                <DialogTitle className="sr-only">Preview Design</DialogTitle>
                <DialogDescription className="sr-only">Preview your design</DialogDescription>

                {/* --- HEADER --- */}
                <div className="h-16 border-b border-white/10 flex items-center justify-between px-6 bg-zinc-900 z-10 flex-shrink-0">
                    <div className="flex gap-2 p-1 bg-black/40 rounded-lg border border-white/5">
                        
                        {/* FIX: Hide 2D button if it's a mug */}
                        {!isMug && (
                            <button
                                onClick={() => setViewMode('2d')}
                                className={`flex items-center gap-2 px-4 py-1.5 rounded-md text-sm font-medium transition-all ${viewMode === '2d' ? "bg-white text-black shadow-sm" : "text-zinc-400 hover:text-white"}`}
                            >
                                <ImageIcon size={16} /> 2D Mockup
                            </button>
                        )}

                        <button
                            onClick={() => has3D && setViewMode('3d')}
                            disabled={!has3D}
                            className={`flex items-center gap-2 px-4 py-1.5 rounded-md text-sm font-medium transition-all ${viewMode === '3d' ? "bg-white text-black shadow-sm" : "text-zinc-400 hover:text-white"} ${!has3D ? "opacity-40 cursor-not-allowed" : ""}`}
                        >
                            <Box size={16} />
                            {has3D ? "3D View" : "3D Not Available"}
                        </button>
                    </div>
                    <Button variant="ghost" size="icon" onClick={onClose} className="text-zinc-400 hover:text-white rounded-full hover:bg-white/10">
                        <X size={20} />
                    </Button>
                </div>

                {/* --- MAIN STAGE --- */}
                <div className="flex-1 relative w-full bg-zinc-900 overflow-hidden flex">
                    <div className="flex-1 relative flex flex-col min-w-0">

                        {/* === 2D VIEW === */}
                        {viewMode === '2d' && (
                            <div className="flex-1 flex items-center justify-center bg-zinc-900 p-8 overflow-auto">

                                {/* 🖼️ PREVIEW CONTAINER */}
                                <div className="relative w-full max-w-[500px] aspect-[1/1] shadow-2xl rounded-lg overflow-hidden flex items-center justify-center bg-zinc-800">

                                    {/* LAYER 1: The Mug Mockup (Photo) */}
                                    {mockups[activeSide] ? (
                                        <img
                                            src={mockups[activeSide]}
                                            alt={`${activeSide} view`}
                                            className="absolute inset-0 w-full h-full object-fill z-0"
                                        />
                                    ) : (
                                        <div className="text-white">No Mockup Image</div>
                                    )}

                                    {/* LAYER 2: The Design (Warped + Masked) */}
                                    {/* This is where the magic happens. We mask this div to the mug shape */}
                                    <div
                                        className="absolute inset-0 z-10 flex items-center justify-center pointer-events-none"
                                        style={{
                                            // DYNAMIC MASKING: Looks for 'mug-mask-front.png', 'mug-mask-left.png', etc.
                                            maskImage: `url('/assets/mockups/mug-${activeSide}-mask.png')`,
                                            maskSize: 'contain',
                                            maskRepeat: 'no-repeat',
                                            maskPosition: 'center',

                                            WebkitMaskImage: `url('/assets/mockups/mug-${activeSide}-mask.png')`,
                                            WebkitMaskSize: 'contain',
                                            WebkitMaskRepeat: 'no-repeat',
                                            WebkitMaskPosition: 'center',
                                        }}
                                    >
                                        {isProcessing ? (
                                            <Loader2 className="animate-spin text-white" />
                                        ) : isMug && warpedTextureSrc ? (
                                            <img
                                                src={warpedTextureSrc}
                                                alt="Warped Design"
                                                className="w-full h-full object-contain"
                                                style={{
                                                    // Multiply blends the design into the ceramic texture
                                                    mixBlendMode: 'multiply',
                                                    // Slight transparency looks more realistic for dye sublimation
                                                    opacity: 0.95
                                                }}
                                            />
                                        ) : !isMug && getStandardTexture() ? (
                                            // Fallback for T-Shirts
                                            <img
                                                src={getStandardTexture()}
                                                className="w-[50%] h-[50%] object-contain"
                                                style={{ mixBlendMode: 'multiply' }}
                                            />
                                        ) : null}
                                    </div>

                                    {/* LAYER 3: The Glare/Shadow Overlay */}
                                    {/* This sits ON TOP of the design to make it look round */}
                                    {isMug && (
                                        <div
                                            className="absolute w-full inset-0 z-20 pointer-events-none object-fill"
                                            style={{
                                                background: `linear-gradient(90deg, 
                                                    rgba(0,0,0,0.3) 0%, 
                                                    rgba(255,255,255,0.0) 20%, 
                                                    rgba(255,255,255,0.4) 40%, 
                                                    rgba(255,255,255,0.0) 60%, 
                                                    rgba(0,0,0,0.3) 100%)`,

                                                // We mask the shadow too, so it doesn't darken the background
                                                maskImage: `url('/assets/mockups/mug-${activeSide}-mask.png')`,
                                                maskSize: 'contain',
                                                maskRepeat: 'no-repeat',
                                                maskPosition: 'center',
                                                WebkitMaskImage: `url('/assets/mockups/mug-${activeSide}-mask.png')`,
                                                WebkitMaskSize: 'contain',
                                                WebkitMaskRepeat: 'no-repeat',
                                                WebkitMaskPosition: 'center',

                                                mixBlendMode: 'multiply' // or 'overlay' depending on look
                                            }}
                                        />
                                    )}

                                </div>
                            </div>
                        )}

                        {/* === 3D VIEW === */}
                        {viewMode === '3d' && has3D && (
                            <div className="w-full h-full">
                                <Tshirt3DPreview
                                    modelUrl={productData.model3d}
                                    textures={{
                                        front: textures.front?.url,
                                        back: textures.back?.url,
                                        leftSleeve: textures.leftSleeve?.url,
                                        rightSleeve: textures.rightSleeve?.url
                                    }}
                                    color={selectedColor}
                                />
                            </div>
                        )}

                        {/* === FOOTER: THUMBNAILS === */}
                        {mockupKeys.length > 1 && isMug && (
                            <div className="h-24 border-t border-white/10 bg-zinc-950 flex items-center justify-center gap-4 flex-shrink-0 z-30">
                                {mockupKeys.map(side => (
                                    <button
                                        key={side}
                                        onClick={() => setActiveSide(side)}
                                        className={`relative w-16 h-16 rounded-lg border-2 overflow-hidden transition-all ${activeSide === side ? "border-white scale-110" : "border-white/20 opacity-60 hover:opacity-100"}`}
                                    >
                                        <img src={mockups[side]} alt={side} className="w-full h-full object-cover" />
                                    </button>
                                ))}
                            </div>
                        )}
                    </div>
                </div>
            </DialogContent>
        </Dialog>
    );
}